# MIT License
#
# Copyright (c) 2023 Clivern
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


vars:
  version: 0.1.2
  api_url: https://pinkman.free.beeceptor.com
  api_key: 5ab99869-f403-4481-bed6-da7c8aad7521
  port: 1025
  hostname: localhost

templates:
  config.pinkman.prod.yml.j2: config.pinkman.prod.yml.j2
  pinkman_server.service.j2: pinkman_server.service.j2
  pinkman_worker.service.j2: pinkman_worker.service.j2

tasks:
  - name: Install pinkman
    command: "pip install pinkman=={{ version }}"

  - name: Create config files
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
    with_items:
      - { src: "config.pinkman.prod.yml.j2", dest: "/etc/config.pinkman.prod.yml", mode: "0700" }
      - { src: "pinkman_server.service.j2", dest: "/etc/systemd/system/pinkman_server.service", mode: "0644" }
      - { src: "pinkman_worker.service.j2", dest: "/etc/systemd/system/pinkman_worker.service", mode: "0644" }

handlers:
  - name: restart pinkman_server
    service:
      name: pinkman_server
      state: restarted
      enabled: yes

  - name: restart pinkman_worker
    service:
      name: pinkman_worker
      state: restarted
      enabled: yes
